# GitHub Organization Secrets Configuration
# This file defines what secrets are needed for bot projects

organization_secrets:
  required_secrets:
    # Core Bot Secrets (project-specific)
    - name: TELEGRAM_BOT_TOKEN
      description: "Telegram Bot API token from @BotFather"
      visibility: selected
      prefixed: true  # Will be prefixed with project name
      
    - name: DATABASE_URL
      description: "PostgreSQL connection string"
      visibility: selected
      prefixed: true
      
    # Deployment Secrets (shared or project-specific)
    - name: DEPLOY_SSH_KEY
      description: "SSH private key for server deployment"
      visibility: selected
      prefixed: false  # Shared across projects
      
    - name: SERVER_HOST
      description: "Deployment server hostname or IP"
      visibility: selected
      prefixed: true  # Different servers per project
      
    - name: SERVER_USER
      description: "Deployment server username"
      visibility: selected
      prefixed: true  # Different users per project
      
    # Optional AI Integration
    - name: OPENROUTER_API_KEY
      description: "OpenRouter API key for AI functionality (optional)"
      visibility: selected
      prefixed: true
      
    # Optional Support Bot
    - name: SUPPORT_BOT_TOKEN
      description: "Support bot token (optional)"
      visibility: selected
      prefixed: true
      
    - name: SUPPORT_CHAT_ID
      description: "Admin chat ID for support messages (optional)"
      visibility: selected
      prefixed: true

# Project naming configuration
project_config:
  separator: "_"  # Separator between project name and secret name
  # Example: MYBOT_TELEGRAM_BOT_TOKEN